<?php 
/**
 * Joomi_MasonryGallery extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Joomi
 * @package        Joomi_MasonryGallery
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category list template
 *
 * @category    Joomi
 * @package     Joomi_MasonryGallery
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_categories = $this->getCategories(); ?>
<div class="page-title category-title">
    <h1><?php echo Mage::helper('joomi_masonrygallery')->__('Categories') ?></h1>
</div>
<?php if ($_categories->getSize() > 0) :?>
    <?php if ($this->_getDisplayMode() == 0) : ?>
        <?php echo $this->getPagerHtml(); ?>
        <div class="category-list-container">
            <?php foreach ($_categories as $_category) : ?>
                <div class="category-list-item">
            <a href="<?php echo $_category->getCategoryUrl()?>">
                <?php echo $_category->getTitle();?>
            </a><br />
                </div>
            <?php endforeach;?>
        </div>
        <?php echo $this->getPagerHtml(); ?>
    <?php else : ?>
        <ul id="categories-list">
            <?php foreach ($_categories as $_category) : ?>
                <?php echo $this->drawCategory($_category);?>
            <?php endforeach;?>
        </ul>
        <script type="text/javascript">
            masonrygalleryTree('categories-list');
        </script>
    <?php endif;?>
<?php else : ?>
    <?php echo Mage::helper('joomi_masonrygallery')->__('There are no categories at this moment');?>
<?php endif;?>
