<?php
/**
 * Joomi_MasonryGallery extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Joomi
 * @package        Joomi_MasonryGallery
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category subtree template
 *
 * @category    Joomi
 * @package     Joomi_MasonryGallery
 * @author      Ultimate Module Creator
 */
?>
<?php $_categories = $this->getCategories(); ?>
<?php if ($_categories->getSize() > 0) :?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/joomi_masonrygallery/tree.js')?>"></script>
    <ul id="<?php echo $this->getUniqueId()?>">
        <?php foreach ($_categories as $_category) : ?>
            <?php echo $this->drawCategory($_category);?>
        <?php endforeach;?>
    </ul>
    <script type="text/javascript">
        masonrygalleryTree('<?php echo $this->getUniqueId()?>');
    </script>
<?php endif;?>
