<?php
/**
 * Joomi_MasonryGallery extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Joomi
 * @package        Joomi_MasonryGallery
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category view widget template
 *
 * @category    Joomi
 * @package     Joomi_MasonryGallery
 * @author      Ultimate Module Creator
 */
?>
<?php $_category = $this->getCurrentCategory();?>
<?php if ($_category) :?>
    <div class="category-widget-view">
        <h3><?php echo $_category->getTitle()?></h3>
        <div>
            <div class="title-widget">
                <?php echo Mage::helper('joomi_masonrygallery')->__('Title');?>:<?php echo $_category->getTitle();?>
            </div>
            <div class="description-widget">
                <?php echo Mage::helper('joomi_masonrygallery')->__('Description');?>:<?php echo $_category->getDescription();?>
            </div>
            <div class="ordering-widget">
                <?php echo Mage::helper('joomi_masonrygallery')->__('Ordering');?>:<?php echo $_category->getOrdering();?>
            </div>

        </div>
    </div>
<?php endif;?>
