<?php
/**
 * Joomi_MasonryGallery extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Joomi
 * @package        Joomi_MasonryGallery
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Gallery link widget template
 *
 * @category    Joomi
 * @package     Joomi_MasonryGallery
 * @author      Ultimate Module Creator
 */
?>
<?php $_gallery = $this->getCurrentGallery();?>
<?php if ($_gallery) :?>
    <div class="gallery-widget-link">
        <a href="<?php echo $_gallery->getGalleryUrl()?>"><?php echo $_gallery->getTitle()?></a>
    </div>
<?php endif;?>
