<?php
/**
 * Joomi_MasonryGallery extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Joomi
 * @package        Joomi_MasonryGallery
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<div class="content-header">
    <h3 class="icon-head head-categories">
        <?php echo $this->htmlEscape($this->getHeader()) . ($this->getGalleryId() ? ' (' . Mage::helper('joomi_masonrygallery')->__('ID: %s', $this->getGalleryId()) . ')' : '') ?>
    </h3>
    <p class="content-buttons form-buttons">
        <?php echo $this->getResetButtonHtml() ?>
        <?php if($this->getGalleryId()): ?>
            <?php echo $this->getDeleteButtonHtml() ?>
        <?php endif; ?>
        <?php echo $this->getAdditionalButtonsHtml(); ?>
        <?php echo $this->getSaveButtonHtml() ?>
    </p>
</div>
<?php echo $this->getTabsHtml() ?>
<iframe name="iframeSave" style="display:none; width:100%;" src="<?php echo $this->getJsUrl() ?>blank.html"></iframe>
<form target="iframeSave" id="gallery_edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <div class="no-display">
        <input type="hidden" name="isIframe" value="1" />
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
        <input type="hidden" name="active_tab_id" id="active_tab_id" value="" />
        <input type="hidden" name="gallery_products" id="in_gallery_products" value="" />
    </div>
    <div id="gallery_tab_content"></div>
</form>
<script type="text/javascript">
//<![CDATA[
    galleryForm = new varienForm('gallery_edit_form');
    galleryForm.submit= function (url) {
        this.errorSections = $H({});
        this.canShowError = true;
        this.submitUrl = url;
        if (this.validator && this.validator.validate()) {
            if(this.validationUrl){
                this._validate();
            }
            else{
                if (this.isSubmitted) {
                    return false;
                }
                this.isSubmitted = true;
                this._submit();
            }
            displayLoadingMask();
            return true;
        }
        return false;
    };
    galleryForm.refreshPath = function () {
        galleryId = this.getGalleryId();
        if (!galleryId) {
            return false;
        }
        var refreshPathSuccess = function(transport) {
            if (transport.responseText.isJSON()) {
                response = transport.responseText.evalJSON()
                if (response.error) {
                    alert(response.message);
                }
                else {
                    if (galleryForm.getGalleryId() == response['id']) {
                        galleryForm.setGalleryPath(response['path']);
                    }
                }
            }
        };
        new Ajax.Request(
            '<?php echo $this->getRefreshPathUrl() ?>',
            {
                method: 'POST',
                evalScripts: true,
                onSuccess: refreshPathSuccess
            }
        );
    };

    galleryForm.getGalleryId = function () {
        collection = $(this.formId).getInputs('hidden','gallery[id]');
        if (collection.size() > 0) {
            return collection.first().value;
        }
        return false;
    };
    galleryForm.setGalleryPath = function (path) {
        collection = $(this.formId).getInputs('hidden','gallery[path]');
        if (collection.size() > 0) {
            return collection.first().value = path;
        }
    };
    function gallerySubmit(url, useAjax) {
        var activeTab = $('active_tab_id');
        if (activeTab) {
            if (activeTab.tabsJsObject && activeTab.tabsJsObject.activeTab) {
                activeTab.value = activeTab.tabsJsObject.activeTab.id;
            }
        }
        var params = {};
        var fields = $('gallery_edit_form').getElementsBySelector('input', 'select');
        for(var i=0;i<fields.length;i++){
            if (!fields[i].name) {
                continue;
            }
            params[fields[i].name] = fields[i].getValue();
        }
        var galleryId = params['gallery[id]'] ? params['gallery[id]'] : 0;
        var isCreating = galleryId == 0;
        var path = params['gallery[path]'].split('/');
        var parentId = path.pop();
        if (parentId == galleryId) {
            parentId = path.pop();
        }
        if (isCreating) {
            if (!tree.currentNodeId) {
                tree.currentNodeId = parentId;
            }
            tree.addNodeTo = parentId;
        }
        else {
            var currentNode = tree.getNodeById(galleryId);
            var oldClass = 'active-category';
            var newClass = 'active-category';
            if (currentNode) {
                if (parseInt(params['gallery[status]'])) {
                    var oldClass = 'no-active-category';
                    var newClass = 'active-category';
                }
                else {
                    var oldClass = 'active-category';
                    var newClass = 'no-active-category';
                }
                Element.removeClassName(currentNode.ui.wrap.firstChild, oldClass);
                Element.addClassName(currentNode.ui.wrap.firstChild, newClass);
            }
        }
        galleryForm.submit();
    }
    <?php if(($block = $this->getLayout()->getBlock('gallery.product.grid')) && ($_gridJsObject=$block->getJsObjectName())): ?>
        var galleryProducts = $H(<?php echo $this->getProductsJson() ?>);
        $('in_gallery_products').value = galleryProducts.toQueryString();
        function registerGalleryProduct(grid, element, checked){
        if(checked){
            if(element.positionElement){
                element.positionElement.disabled = false;
                galleryProducts.set(element.value, element.positionElement.value);
            }
        }
        else{
            if(element.positionElement){
                element.positionElement.disabled = true;
            }
            galleryProducts.unset(element.value);
        }
        $('in_gallery_products').value = galleryProducts.toQueryString();
            grid.reloadParams = {'selected_products[]':galleryProducts.keys()};
        }
        function galleryProductRowClick(grid, event){
            var trElement = Event.findElement(event, 'tr');
            var isInput   = Event.element(event).tagName == 'INPUT';
            if(trElement){
                var checkbox = Element.getElementsBySelector(trElement, 'input');
                if(checkbox[0]){
                    var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                    <?php echo $_gridJsObject ?>.setCheckboxChecked(checkbox[0], checked);
                }
            }
        }
        function positionChange(event){
            var element = Event.element(event);
            if(element && element.checkboxElement && element.checkboxElement.checked){
            galleryProducts.set(element.checkboxElement.value, element.value);
                $('in_gallery_products').value = galleryProducts.toQueryString();
            }
        }
        var tabIndex = 1000;
        function galleryProductRowInit(grid, row){
            var checkbox = $(row).getElementsByClassName('checkbox')[0];
            var position = $(row).getElementsByClassName('input-text')[0];
            if(checkbox && position){
                checkbox.positionElement = position;
                position.checkboxElement = checkbox;
                position.disabled = !checkbox.checked;
                position.tabIndex = tabIndex++;
                Event.observe(position,'keyup',positionChange);
            }
        }
        <?php echo $_gridJsObject ?>.rowClickCallback = galleryProductRowClick;
        <?php echo $_gridJsObject ?>.initRowCallback = galleryProductRowInit;
        <?php echo $_gridJsObject ?>.checkboxCheckCallback = registerGalleryProduct;
        <?php echo $_gridJsObject ?>.rows.each(function(row){
            galleryProductRowInit(<?php echo $_gridJsObject ?>, row)
        });
    <?php endif; ?>
    <?php if($this->isAjax() && ($block = $this->getLayout()->getBlock('tabs')) && ($_tabsJsObject=$block->getJsObjectName())): ?>
        <?php echo $_tabsJsObject ?>.moveTabContentInDest();
        if (<?php echo $_tabsJsObject ?>.activeTab) {
            $('active_tab_id').value = <?php echo $_tabsJsObject ?>.activeTab.id;
        }
        $('active_tab_id').tabsJsObject = <?php echo $_tabsJsObject ?>;
    <?php endif; ?>
//]]>
</script>
